import { Roast } from "./types";

export default [
  {
    name: "Yirgacheffe",
    origin: "Ethiopia",
    roaster: "Old Town Roasters",
    price: 15,
    weight: 250,
    roast: Roast.Medium,
    flavorNotes: ["blueberry", "citrus", "floral"],
  },
  {
    name: "Winter Kenya Blend",
    origin: "Kenya",
    roaster: "Pike Place Roasters",
    price: 20,
    weight: 250,
    roast: Roast.Light,
    flavorNotes: ["black currant", "cocoa", "spice"],
  },
  {
    name: "Pantano",
    origin: "Brazil",
    roaster: "Dreamland Roasters",
    price: 18,
    weight: 250,
    roast: Roast.Dark,
    flavorNotes: ["nutty", "chocolate", "caramel"],
  },
  {
    name: "Letty Bermuzdez Geisha",
    origin: "Colombia",
    roaster: "Lightsail Coffee Roasters",
    price: 20,
    weight: 12,
    roast: Roast.Light,
    flavorNotes: ["chocolate", "nutty"],
  },
  {
    name: "Hacienda Blend",
    origin: "Brazil",
    roaster: "Highland Coffee",
    price: 25,
    weight: 12,
    roast: Roast.Medium,
    flavorNotes: ["fruity", "nutty"],
  },
  {
    name: "Kirinyaga Peaberry",
    origin: "Kenya",
    roaster: "Black Sheep Roasters",
    price: 30,
    weight: 12,
    roast: Roast.Dark,
    flavorNotes: ["spicy", "nutty"],
  },
];
