import { Roast } from "./types";

export default [
  {
    name: "Yirgacheffe",
    origin: "Ethiopia",
    roaster: "Old Town Roasters",
    price: 15,
    weight: 250,
    roast: Roast.Medium,
    flavorNotes: ["blueberry", "citrus", "floral"],
    img: "pexels-interwebly-18138946.jpg",
  },
  {
    name: "Winter Kenya Blend",
    origin: "Kenya",
    roaster: "Pike Place Roasters",
    price: 20,
    weight: 250,
    roast: Roast.Light,
    flavorNotes: ["black currant", "cocoa", "spice"],
    img: "pexels-mlkbnl-10251415.jpg",
  },
  {
    name: "Pantano",
    origin: "Brazil",
    roaster: "Dreamland Roasters",
    price: 18,
    weight: 250,
    roast: Roast.Dark,
    flavorNotes: ["nutty", "chocolate", "caramel"],
    img: "pexels-photo-14385408.webp",
  },
  {
    name: "Letty Bermuzdez Geisha",
    origin: "Colombia",
    roaster: "Lightsail Coffee Roasters",
    price: 20,
    weight: 12,
    roast: Roast.Light,
    flavorNotes: ["chocolate", "nutty"],
    img: "pexels-raymond-petrik-1448389535-28642476.jpg",
  },
  {
    name: "Hacienda Blend",
    origin: "Brazil",
    roaster: "Highland Coffee",
    price: 25,
    weight: 12,
    roast: Roast.Medium,
    flavorNotes: ["fruity", "nutty"],
    img: "pexels-vikeph-17312403.jpg",
  },
  {
    name: "Kirinyaga Peaberry",
    origin: "Kenya",
    roaster: "Black Sheep Roasters",
    price: 30,
    weight: 12,
    roast: Roast.Dark,
    flavorNotes: ["spicy", "nutty"],
  },
];
